# This is a basic workflow to help you get started with Actions

name: plokkkun

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  build:

    runs-on: windows-latest

    timeout-minutes: 9999

    steps:

    - name: Mendownload Ngrok.

      run: |

        Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip

        Invoke-WebRequest https://raw.githubusercontent.com/molkiuhyg/aguet/main/start.bat -OutFile start.bat

        Invoke-WebRequest https://raw.githubusercontent.com/molkiuhyg/aguet/main/wallpaper.png -OutFile wallpaper.png

        Invoke-WebRequest https://raw.githubusercontent.com/molkiuhyg/aguet/main/wallpaper.bat -OutFile wallpaper.bat

        Invoke-WebRequest https://raw.githubusercontent.com/molkiuhyg/aguet/main/loop.bat -OutFile loop.bat

    - name: Mendownload Launcher.

      run: |

        Invoke-WebRequest https://github.com/molkiuhyg/aguet/raw/main/launcher/Node.js.lnk -OutFile Node.js.lnk

        Invoke-WebRequest https://github.com/molkiuhyg/aguet/raw/main/launcher/Visual%20Studio%202019.lnk -OutFile "Visual Studio 2019.lnk"

        Invoke-WebRequest https://github.com/molkiuhyg/aguet/raw/main/launcher/Ganti%20Password.exe -OutFile "Ganti Password.exe"

    - name: Mengextract Ngrok File.

      run: Expand-Archive ngrok.zip

    - name: Connect Ke Akun Ngrok.

      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN

      env:

        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Mengaktifkan Akses RDP.

      run: | 

        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0

        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1

        copy wallpaper.bmp D:\a\wallpaper.bmp

        copy wallpaper.bat D:\a\wallpaper.bat

        copy Node.js.lnk C:\Users\Public\Desktop\Node.js.lnk

        copy "Visual Studio 2019.lnk" "C:\Users\Public\Desktop\Visual Studio 2019.lnk"

        copy "Ganti Password.exe" "C:\Users\Public\Desktop\Ganti Password.exe"

    - name: Membuat Tunnel.

      run: Start-Process Powershell -ArgumentList '-Noexit -Command ".\ngrok\ngrok.exe tcp --region ap 3389"'

    - name: Connect Ke RDP Kamu CPU 2 Core - 7GB Ram - 255 SSD.

      run: cmd /c start.bat

    - name: Berhasil Dibuat! Anda Bisa Menutup Tab Sekarang.

      run: cmd /c loop.bat
